### ISSUE TITLE
Spray animation bugs minigun

### ISSUE THREAD

**Issue by neguma** [DrAbcOfficial/AngelScripts#2]
hi DrAbc, apologies for bothering you with something that's 3+ years old, but i don't know what else to do (i'm no programmer but i understand code to some extent so i've tried modifying things in the code, to no success)

i'm having a problem with you spray animation plugin. it works as intended, however, when you have a minigun and do the spray thing, after the animation is finished, you can't shoot or drop the minigun anymore, the only way out is suicide. this only happens with the minigun.

can this be fixed, please? or at least, could you point me in the right direction as to what should be modified in the code for this to not happen? thank you very much

**Comment by DrAbcOfficial** [comment]
I added a simple check to bypass minigun and now it should be fine

**Comment by neguma** [comment]
I was able to test it today, issue resolved! Thank you so much DrAbc

**Comment by neguma** [comment]
I was able to test it today, issue solved! Thank you so much DrAbc
