### ISSUE TITLE
Squad Respawn Menu Number

### ISSUE THREAD

**Issue by darkfvtvre** [DrAbcOfficial/AngelScripts#4]
![image](https://github.com/user-attachments/assets/24374eac-638b-4a94-8867-2bb9b03dbd20)
Why is there an extra number when you choose a player?  Is that the number of the player on the list?  Is there a way to remove that extra number?

Diregard the previous edit.  I thought I fixed it, but I did not.

**Comment by DrAbcOfficial** [comment]
https://github.com/DrAbcOfficial/AngelScripts/blob/cee2b33ce9600efa93bd6f53647ac0aadcf1474d/SquardRespawn.as#L61
here, delete `+tPlayer.entindex()`
